---
title: "League of Legends Data Analysis"
author: "Vincent Quenneville-Bélair"
date: "March, 2016"
output: html_document
---

Loading packages.
```{r}
# https://cran.r-project.org/web/packages/tidyjson/vignettes/introduction-to-tidyjson.html
# https://github.com/sailthru/tidyjson
library("tidyjson")

library(plyr)
library(magrittr)
library(tidyr)
library(dplyr)
library(stringr)

library(ggplot2)
library(rattle)

library(caret)
library(pROC)
```

```{r}
# Read RIOT API key
# riot.key <- readLines("riot.key")
# options("riot.key" = riot.key)
```

Load match file.
```{r}
# TidyJSON
data.file <- "data/matches1.json"
# data.file <- "data/matches_all.json"
data.json <- read_json(data.file)
```

Load information from each match.
```{r}
data.match <- data.json %>% 
  # gather_array("file.index") %>%
  enter_object("matches") %>%
  gather_array("matches.index") %>% 
  spread_values(matchId = jnumber("matchId")) %>%
  select(matchId) 
```

Match duration
```{r}
data.match %>%
  spread_values(mapId = jnumber("mapId"),
                matchDuration = jnumber("matchDuration"),
                matchMode = jstring("matchMode"),
                matchType = jstring("matchType"),
                queueType = jstring("queueType"),
                region = jstring("region"),
                season = jstring("season")) %>%
  head()

data.match %>%
  spread_values(matchDuration = jnumber("matchDuration")) %>%
  mutate(matchDuration = matchDuration/60) %>%
  select(matchDuration) %>%
  summary

#  matchDuration  
#  Min.   :27.33  
#  1st Qu.:31.83  
#  Median :35.01  
#  Mean   :35.99  
#  3rd Qu.:38.62  
#  Max.   :52.15  

match.duration <- data.match %>%
  spread_values(matchDuration = jnumber("matchDuration")) %>%
  mutate(matchDuration = matchDuration/60) 

timeline.castle <- match.duration %>%
  summarise(timestamp = median(matchDuration)) %>%
  mutate(eventType = "CASTLE")
```

We make the table of winner per match.
```{r}
match.winner <- data.match %>%
  select(matchId) %>%
  enter_object("teams") %>%
  gather_array("teams.index") %>%
  select(-teams.index) %>%
  spread_values(teamId = jnumber("teamId"),
                winner = jlogical("winner")) %>%
  mutate(winner = winner * teamId) %>%
  group_by(matchId) %>%
  summarise_each(funs(sum)) %>%
  select(-teamId) %>%
  mutate_each(funs(factor))
```

Is there an advantage being on the blue/red side?
```{r}
match.winner %>% 
  select(winner) %>%
  summary()

#  winner  
#  100:53  
#  200:47  
```

```{r}
match.events <- data.match %>%
  enter_object("timeline") %>%
  enter_object("frames") %>%
  gather_array("frames.index") %>%
  enter_object("events") %>%
  gather_array("events.index") %>%
  select(matchId) %>%
  spread_values(eventType = jstring("eventType"),
                teamId = jnumber("teamId"),
                participantId = jnumber("participantId"), 
                timestamp = jnumber("timestamp"),
                creatorId = jnumber("creatorId"),
                monsterType = jstring("monsterType"),
                victimId = jnumber("victimId"),
                killerId = jnumber("killerId"),
                position = jstring("position")) %>%
  mutate(timestamp = timestamp/1000/60)
```

Proportion of matches that ends in surrender.
```{r}
match.team <- data.match %>%
  select(matchId) %>%
  enter_object("teams") %>%
  gather_array("teams.index") %>%
  select(-teams.index) %>%
  spread_values(teamId = jnumber("teamId"),
                winner = jlogical("winner"))

# Extract tower information to infer whether losing team surrendered
match.turret <- match.events %>%
  spread_values(towerType = jstring("towerType")) %>%
  filter(towerType == "NEXUS_TURRET") %>%
  mutate(NEXUS_TURRET = 1) %>%
  select(matchId, teamId, NEXUS_TURRET)

match.surrender <- merge(match.team, match.turret, all.x = TRUE) %>%
  group_by(matchId, teamId, winner) %>%
  summarise_each(funs(sum)) %>%
  mutate(surrender = ifelse(winner, FALSE, 
                            ifelse(NEXUS_TURRET < 2 | is.na(NEXUS_TURRET), TRUE, FALSE))) %>%
  group_by(matchId) %>%
  summarise_each(funs(sum)) %>%
  select(matchId, surrender) %>%
  mutate(surrender = as.logical(surrender))

merge(match.duration, match.surrender) %>%
  group_by(surrender) %>%
  summarise_each(funs(median)) %>%
  select(-matchId)

# Percent of matches that ended in surrender?
x <- match.surrender$surrender
print(sum(x) / length(x) * 100)
```

When are certain objectives achieved for the time in a match?
```{r}
# BARON_NASHOR, BLUE_GOLEM, DRAGON, RED_LIZARD, RIFTHERALD, VILEMAW
match.events %>%
  filter(monsterType == "DRAGON") %>%
  select(matchId, timestamp) %>%
  group_by(matchId) %>%
  mutate(rank = rank(timestamp, na.last = TRUE, ties.method = "first")) %>%
  filter(rank == 1) %>%
  select(-rank)

# Compute median time when first elite monster is killed
timeline.monster <- match.events %>%
  filter(eventType == "ELITE_MONSTER_KILL") %>%
  select(matchId, timestamp, monsterType) %>%
  group_by(matchId, monsterType) %>%
  mutate(rank = rank(timestamp, na.last = TRUE, ties.method = "first")) %>%
  filter(rank == 1) %>%
  as.data.frame() %>%
  select(timestamp, monsterType) %>%
  group_by(monsterType) %>%
  summarise_each(funs(median)) %>%
  mutate(eventType = monsterType) %>%
  select(-monsterType) %>%
  mutate(eventType = str_replace(eventType, "BARON_NASHOR", "BARON"),
         eventType = str_replace(eventType, "RIFTHERALD", "HERALD"))

# Compute the median time to draw first blood
timeline.kill <- match.events %>%
  filter(eventType == "CHAMPION_KILL") %>% 
  select(matchId, timestamp) %>%
  group_by(matchId) %>%
  mutate(rank = rank(timestamp, na.last = TRUE, ties.method = "first")) %>%
  filter(rank == 1) %>%
  as.data.frame() %>%
  summarise(timestamp = median(timestamp)) %>%
  mutate(eventType = "CHAMPION KILL")

# Compute the median time to reach level 18
timeline.maxlvl <- match.events %>%
  filter(eventType == "SKILL_LEVEL_UP") %>%
  mutate(teamId = ifelse(participantId <= 5, 100, 200)) %>%
  select(matchId, timestamp, teamId) %>%
  group_by(matchId, teamId) %>%
  mutate(rank = rank(timestamp, na.last = TRUE, ties.method = "first")) %>%
  filter(rank == 5*18) %>%
  as.data.frame() %>%
  summarise(timestamp = median(timestamp)) %>%
  mutate(eventType = "MAX LEVEL")

# Compute the median level reached
match.events %>%
  filter(eventType == "SKILL_LEVEL_UP") %>%
  mutate(teamId = ifelse(participantId <= 5, 100, 200)) %>%
  select(matchId, timestamp, teamId) %>%
  group_by(matchId, teamId) %>%
  mutate(rank = rank(timestamp, na.last = TRUE, ties.method = "first")) %>%
  select(-timestamp) %>%
  summarise_each(funs(max(rank))) %>%
  as.data.frame() %>%
  summarise(rank = median(rank)/5)

#   rank
# 1 15.5

timeline <- rbind(timeline.monster, timeline.castle, timeline.kill, timeline.maxlvl)
timeline <- match[order(match$timestamp),]

#   timestamp     eventType
#       (dbl)         (chr)
# 1  3.106833 CHAMPION_KILL
# 2 12.501317        DRAGON
# 3 16.841450    RIFTHERALD
# 4 29.832517  BARON_NASHOR
# 5 35.008333           END
# 6 45.787875       MAX_LVL
  
# Draw timeline
# http://stackoverflow.com/questions/7492274/draw-a-chronological-timeline-with-ggplot2

dislocations <- sample(c(-1,-.5,.5,1), 6, replace=T)
dislocations <- c(1.0, -1.0, 0.5, -0.5, 1.0, -0.5)
nudges <- 0.1 * sign(dislocations)

p <- ggplot(timeline) + 
  geom_text(aes(x = timestamp, y = dislocations, label = eventType), 
            position = position_nudge(y = nudges)) +
  geom_hline(yintercept = 0, color = "purple") +
  geom_segment(aes(x = timestamp, y = dislocations, xend = timestamp, yend = 0)) +
  xlab("minutes") +
  scale_x_continuous(expand = c(.15, .15))

p <- p + 
  theme(axis.line = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none")

print(p)
ggsave("figures/timeline.png", dpi = 100, width = 7, height = 4, units = "in")
```

```{r}
# Delta fields refer to values for the specified period (e.g., the gold per minute over the first 10 minutes of the game versus the second 20 minutes of the game) 
# Diffs fields refer to the deltas versus the calculated lane opponent(s)

data.timeline <- data.match %>%
  enter_object("participants") %>%
  gather_array("participants.index") %>%
  spread_values(participantId = jnumber("participantId"),
                teamId = jnumber("teamId")) %>%
  select(-participants.index) %>%
  enter_object("timeline")

participants.creeps <- data.timeline %>% 
  enter_object("creepsPerMinDeltas") %>%
  gather_keys("ParticipantTimelineData") %>%
  append_values_number("creepsPerMinDeltas")

participants.gold <- data.timeline %>% 
  enter_object("goldPerMinDeltas") %>%
  gather_keys("ParticipantTimelineData") %>%
  append_values_number("goldPerMinDeltas")

# participants.wards <- data.timeline %>% 
#   enter_object("wardsPerMinDeltas") %>%
#   gather_keys("ParticipantTimelineData") %>%
#   append_values_number("ParticipantTimelineValue")

participants.xp <- data.timeline %>% 
  enter_object("xpPerMinDeltas") %>%
  gather_keys("ParticipantTimelineData") %>%
  append_values_number("xpPerMinDeltas")

participants <- merge(participants.creeps, participants.gold)
participants <- merge(participants, participants.xp)

participants <- merge(participants, team) %>%
  group_by(matchId, teamId, ParticipantTimelineData) %>%
  summarise_each(funs(mean), matchId, teamId,
                 ParticipantTimelineData, creepsPerMinDeltas, goldPerMinDeltas, xpPerMinDeltas)

#      matchId teamId ParticipantTimelineData creepsPerMinDeltas goldPerMinDeltas xpPerMinDeltas
#        (dbl)  (dbl)                   (chr)              (dbl)            (dbl)          (dbl)
# 1 2054994244    100             tenToTwenty               3.52           332.18         478.76
# 2 2054994244    100             thirtyToEnd               3.53           438.55         581.97
# 3 2054994244    100          twentyToThirty               3.20           349.30         428.22
# 4 2054994244    100               zeroToTen               3.02           178.06         266.68
# 5 2054994244    200             tenToTwenty               4.60           385.72         462.62
# 6 2054994244    200             thirtyToEnd               3.33           428.66         483.97
```