---
title: "Map"
author: "Vincent Quenneville-Bélair"
date: "March, 2016"
runtime: shiny
output: html_document
---

Loading packages.
```{r}
# https://cran.r-project.org/web/packages/tidyjson/vignettes/introduction-to-tidyjson.html
# https://github.com/sailthru/tidyjson
library("tidyjson")

library(plyr)
library(tidyr)
library(dplyr)
library(stringr)

library(png)
library(grid)
library(ggplot2)
# library("ggthemes")

library(shiny)
```

Load match file.
```{r}
# TidyJSON
data.file <- "data/matches1.json"
# data.file <- "data/matches_all.json"
data.json <- read_json(data.file)
```

Load information from each match.
```{r}
data.match <- data.json %>% 
  # gather_array("file.index") %>%
  enter_object("matches") %>%
  gather_array("matches.index") %>% 
  spread_values(matchId = jnumber("matchId")) %>%
  select(matchId) %>%
  spread_values(mapId = jnumber("mapId"),
                matchDuration = jnumber("matchDuration"),
                matchMode = jstring("matchMode"),
                matchType = jstring("matchType"),
                queueType = jstring("queueType"),
                region = jstring("region"))
```

Determine winning status.
```{r}
match.winner <- data.match %>%
  select(matchId) %>%
  enter_object("teams") %>%
  gather_array("teams.index") %>% 
  spread_values(teamId = jnumber("teamId"),
                winner = jlogical("winner")) %>%
  select(matchId, teamId, winner)
```

Make data frame for events in matches.
```{r}
# Get events information
match.events <- data.match %>%
  enter_object("timeline") %>%
  enter_object("frames") %>%
  gather_array("frames.index") %>%
  enter_object("events") %>%
  gather_array("events.index") %>%
  select(matchId) %>%
  spread_values(eventType = jstring("eventType"),
                timestamp = jnumber("timestamp"),
                participantId = jnumber("participantId"), 
                creatorId = jnumber("creatorId"),
                victimId = jnumber("victimId"),
                killerId = jnumber("killerId"),
                teamId = jnumber("teamId"),
                position = jstring("position")) %>%
  mutate(participantId = ifelse(participantId <= 5, 100, 200),
         creatorId = ifelse(creatorId <= 5, 100, 200),
         victimId = ifelse(victimId <= 5, 200, 100),   # associate non-victim team!
         killerId = ifelse(killerId <= 5, 100, 200),
         teamId = ifelse(teamId == 100, 200, 100)) # associate to non-victim team! 

# Fill in team association
match.events <- match.events %>%
  mutate(victimId      = ifelse(is.na(victimId), killerId, victimId)) %>%
  mutate(creatorId     = ifelse(is.na(creatorId), victimId, creatorId)) %>%
  mutate(participantId = ifelse(is.na(participantId), creatorId, participantId)) %>%
  mutate(teamId        = ifelse(is.na(teamId), participantId, teamId)) %>%
  select(-participantId,-creatorId,-victimId, -killerId) 

# Attach winning status
match.events <- merge(match.events, match.winner, 
                      by = intersect(names(match.events), names(match.winner)), all.x = TRUE)

# Function to merge a list  
contract <- function(x) {
  paste(x, collapse = ' ')
} 

# Extract position (x,y)
match.events <- match.events %>%
  mutate(position = sapply(str_extract_all(position, "[[:digit:]]+"), contract)) %>%
  as.data.frame() %>%
  separate(position, c("X", "Y")) %>%
  mutate(X = as.numeric(X),
         Y = as.numeric(Y)) 

# Turn into factors
match.events <- match.events %>%
  mutate(eventType = as.factor(eventType),
         teamId = as.factor(teamId))

# Convert timestamps in ms to min
match.events <- match.events %>%
  mutate(timestamp = timestamp/1000/60)
```

# Event versus time

Plot events versus time.
```{r}
# Select one match
data <- match.events %>%
  # filter(matchId == 2054994244) %>%
  # filter(eventType %in% 
  #          c("BUILDING_KILL", "CHAMPION_KILL", "ELITE_MONSTER_KILL", 
  #            "SKILL_LEVEL_UP", "WARD_PLACED")) %>%
  filter(eventType == "CHAMPION_KILL")

# Line plot  
# p <- ggplot(data, aes(x = timestamp, y = ..count.., color = winner, group = winner)) + xlab("time (min)")
# Density plot
# p <- p + geom_density(adjust = 0.25)
# Counting line
# p <- p + geom_freqpoly(binwidth = 5)
# Counting line
# p <- p + stat_bin(binwidth = 5, geom="line", position = "identity")

# Counting bins
p <- ggplot(data, aes(timestamp, y = ..count.., 
                       group = winner, fill = winner)) + 
  # theme_pander() + scale_colour_pander() + scale_fill_pander() +
  xlab("time (min)") +
  stat_bin(binwidth = 5, alpha = 0.7, 
           col = I("white"), position = "identity")

# TODO take into account game finishing early
plot(p)
```

```{r}
# Try to normalize by binwidth
binwidth <- 5

data <- match.events %>%
  mutate(bin = timestamp %/% binwidth) %>%
  filter(eventType == "CHAMPION_KILL")
```

Interactive version.
```{r}
shinyUI(fluidPage(
fluidRow(
column(4, selectInput("eventType", "Type:", 
                      c(unique(as.character(match.events$eventType))), selected = "CHAMPION_KILL")),
column(4, selectInput("matchId", "Match ID:", 
                      c(unique(as.character(match.events$matchId)))))
),
fluidRow(
renderPlot({
  
    data <- match.events %>%
      filter(eventType == input$eventType & matchId == input$matchId)
    
    binwidth <- 2

    # draw the histogram with the specified number of bins
    p <- ggplot(data, aes(timestamp, y = ..count.., 
                          group = winner, fill = winner)) + 
      xlab("time (min)") +
      stat_bin(binwidth = 5, alpha = 0.3, 
               col = I("white"), position = "identity")
 
    plot(p)

  })
)
))
```

# Map overlay

We transform the coordinate given in data frame to coordinate on the image.
```{r}
# We need to apply a linear transformation 
# mapping the given coordinates to the corresponding pixels on the image

# Coordinate range in data frame
# min: {x: 0, y: 0}
# max: {x: 14820, y: 14881}
# Coordinate range on map
# min: {x: -570, y: -420}
# max: {x: 15220, y: 14980}
# Image pixel coordinates
# min: {x: 0, y: 0}
# max: {x: 512, y: 512}

f.x <- function(x) {
  # Input range -570 to 15220
  # Output range 0 to 512
  
  i.xmin = -570
  i.xmax = 15220
  o.xmin = 0
  o.xmax = 512
  
  o.xmin + (o.xmax - o.xmin) * (x - i.xmin) / (i.xmax - i.xmin)
}

f.y <- function(y) {
  # Input range -420 to 14980
  # Output range 0 to 512
  
  i.ymin = -420
  i.ymax = 14980
  o.ymin = 0
  o.ymax = 512
  
  o.ymin + (o.ymax - o.ymin) * (y - i.ymin) / (i.ymax - i.ymin)
}

# Extract the positions of all events in a given match
# ... and apply transformation to find corresponding pixel on image
coord <- match.events %>% 
  mutate(X = f.x(X), Y = f.y(Y))

# Leave buildings as a separate color
# coord <- coord %>%
#   mutate(teamId = ifelse(eventType == "BUILDING_KILL", NA, teamId)) 
```

We plot the events of a match over the map.
```{r}
# Pick one match to map
data <- coord %>%
  filter(matchId == 2054994244)

# Get background image
img <- readPNG("data/minimap-mh.png")
g <- rasterGrob(img, interpolate=TRUE, width=unit(1,"npc"), height=unit(1,"npc"))

# Scatter plot with background
p <- ggplot(data, aes(X, Y, color = teamId, group = teamId)) + 
  scale_color_manual(na.value = "black", values = c("blue","red")) +
  annotation_custom(g, xmin = 0, xmax = 512, ymin = 0, ymax = 512) +
  expand_limits(x = c(0,512), y = c(0,512))

p <- p + geom_point(alpha = 0.5, size = 3)
# p <- p + stat_density2d(aes(fill = ..level..), geom = "polygon", alpha = 0.2) + scale_fill_gradientn(colors = c("blue", "red"))
# p <- p +  stat_bin2d(aes(fill = ..count..), binwidth = 5, alpha = 0.2) +
#   scale_fill_gradientn(colors = c("blue", "red")) +
#   stat_density2d(geom = "polygon", alpha = 0.3)

# Remove padding and decorations
p <- p +
  scale_y_continuous(expand = c(0,0)) + 
  scale_x_continuous(expand = c(0,0)) +
  theme(axis.line = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          legend.position = "none",
          panel.background = element_blank(),
          panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          plot.background = element_blank())

# Show and save plot
print(p)
ggsave("figures/events.png", dpi = 51.2, width = 10, height = 10, units = "in")
```

Interactive version.
```{r}
shinyUI(fluidPage(
fluidRow(
column(4, selectInput("eventType", "Type:", 
                      c("All", unique(as.character(match.events$eventType))), selected = "CHAMPION_KILL")),
column(4, selectInput("matchId", "Match ID:", 
                      c("All", unique(as.character(match.events$matchId)))))
),
fluidRow(
renderPlot({

      data <- coord
  
      if (input$matchId != "All") {
        data <- data %>%
          filter(matchId == input$matchId)
      }
      
      if (input$eventType != "All") {
        data <- data %>%
          filter(eventType == input$eventType)
      }
    
    binwidth <- 2

# Scatter plot with background
p <- ggplot(data, aes(X, Y, color = teamId)) + 
  scale_color_manual(na.value = "black", values = c("blue","red")) +
  annotation_custom(g, xmin = 0, xmax = 512, ymin = 0, ymax = 512) +
  geom_point(alpha = 0.5, size = 3) +
  expand_limits(x = c(0,512), y = c(0,512))

# Remove padding and decorations
p <- p +
  scale_y_continuous(expand = c(0,0)) + 
  scale_x_continuous(expand = c(0,0)) +
  theme(axis.line = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          legend.position = "none",
          panel.background = element_blank(),
          panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          plot.background = element_blank())

# Show and save plot
print(p)

  })
)
))
```